VOLUME_NAME=panmhcb2m_run3

VOLUME_NAME=${VOLUME_NAME} TIMEOUT_HOURS=24 GPU=L40S uvx modal run modal_proteinhunter.py \
	--protein-seqs IQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM:GSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDQETRNVKAQSQTDRVDLGTLRGYYNQSEAGSHTIQIMYGCDVGSDGRFLRGYRQDAYDGKDYIALNEDLRSWTAADMAAQITKRKWEAAHEAEQLRAYLDGTCVEWLRRYLENGKETLQRTDPPKTHMTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWELS \
	--template-path 7UC5.cif,7UC5.cif \
	--template-cif-chain-id B,A \
	--msa-mode single \
	--min-protein-length 60 \
	--max-protein-length 200 \
	--high-iptm-threshold 0.7 \
	--contact-residues '46,85,87,92,93' \
	--percent-x 30 \
	--num-designs 1650 \
	--num-cycles 20 \
	--num-gpus 33 \
	--name ${VOLUME_NAME}

mkdir volume_data && uvx modal volume get $VOLUME_NAME / volume_data --force
