VOLUME_NAME=gpc3_run16
VOLUME_NAME=$VOLUME_NAME TIMEOUT_MINUTES=1400 GPU=B200 uvx modal run modal_proteinhunter.py \
	--protein-ids C \
	--protein-msas "" \
	--name gpc3_run16 \
	--percent-x 30 \
	--min-design-protein-length 50 \
	--max-design-protein-length 150 \
	--high-iptm-threshold 0.7 \
	--contact-residues 67,71,147,153,156,275 \
	--use-potentials \
	--num-designs 1000 \
	--num-cycles 20 \
	--num-gpus 50 \
	--protein-seqs GSDLQVCLPKGPTCCSRKMEEKYQLTARLNMEQLLQSASMELKFLIIQNAAVFQEAFEIVVRHAKNYTNAMFKNNYPSLTPQAFEFVGEFFTDVSLYILGSDINVDDMVNELFDSLFPVIYTQLMNPGLPDSALDINECLRGARRDLKVFGNFPKLIMTQVSKSLQVTRIFLQALNLGIEVINTTDHLKFSKDCGRMLTRMWYCSYCQGLMMVKPCGGYCNVVMQGCMAGVVEIDKYWREYILSLEELVNGMYRIYDMENVLLGLFSTIHDSIQYVQKNAGKLTTTIGKLCAHSQQRQYRSAYYPEDLFIDKKVLKVAHVEHEETLSSRRRELIQKLKSFISFYSALPGYICSHSPVAENDTLCWNGQELVERYSQKAARNGMKNQFNLHELKMKGPEPVVSQIIDKLKHINQLLRTMS 
#	--template-path ./gpc3_af3.cif \
#	--template-chain-id A \
#	--protein-ids A \

uvx modal volume get $VOLUME_NAME / volume_data --force
